config/routes.rb
Rails.application.routes.draw do

  root "main#index"
  get "/invite/:refCode" => "main#invite"
  
  get "/admin" => "admin/login#new"
  post "/admin" => "admin/login#login"
  delete "/admin/logout" => "admin/login#logout"
  get "/admin/dashboard" => "admin/dashboard#index"  
  namespace :admin do
      resources :app_banners
      resources :app_opens
      resources :device_details
      resources :favourites
      resources :generated_qrs
      resources :qr_data
      resources :recently_addeds
      resources :redeems
      resources :redeem_histories
      resources :user_details
      get '/search-user' => 'user_details#index'
      get '/search-device' => 'device_details#index'
  end

  mount API::Base => "/"

end

app/models/app_banner.rb
class AppBanner < ApplicationRecord
end

app/models/app_open.rb
class AppOpen < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/device_detail.rb
class DeviceDetail < ApplicationRecord
  has_many :recently_added
  has_many :qr_data
  has_many :generated_qrs
  has_many :favourites
  has_and_belongs_to_many :user_detail

  def self.search(search)
    where("deviceId LIKE ? OR deviceName LIKE ? OR security_token LIKE ? OR advertisingId LIKE ?", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%") 
  end
end

app/models/favourite.rb
class Favourite < ApplicationRecord
  belongs_to :device_detail
end

app/models/generated_qr.rb
class GeneratedQr < ApplicationRecord
  has_one_attached :codeImage
  belongs_to :device_detail
end

app/models/manager.rb
class Manager < ApplicationRecord
  has_secure_password
end

app/models/qr_datum.rb
class QrDatum < ApplicationRecord
  belongs_to :device_detail
end

app/models/recently_added.rb
class RecentlyAdded < ApplicationRecord
  belongs_to :device_detail
end

app/models/redeem.rb
class Redeem < ApplicationRecord
  belongs_to :user_detail
end

app/models/traffic_request.rb
class TrafficRequest < ApplicationRecord
end

app/models/transaction_history.rb
class TransactionHistory < ApplicationRecord
  belongs_to :user_detail
end

app/models/user_detail.rb
class UserDetail < ApplicationRecord
  has_many :transaction_histories
  has_many :redeems
  has_and_belongs_to_many :device_detail

  def self.search(search)
    where("socialEmail LIKE ? OR socialName LIKE ? OR refCode LIKE ? OR advertisingId LIKE ?", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%") 
  end

end

app/controllers/admin/admin_controller.rb
module Admin
  class AdminController < ApplicationController
    PER_PAGE = 25
    
    def authenticate_user!
      redirect_to admin_path unless current_user
    end

    def current_user
      session[:admin_authenticated] == true
    end
  end
end

app/controllers/admin/device_details_controller.rb
module Admin
    class DeviceDetailsController < Admin::AdminController
        before_action :authenticate_user!
        layout "admin"

        def index2
          #@deviceDetails = DeviceDetail.all.order("id DESC").paginate(:page => params[:page], :per_page => 10)
          @deviceDetails = DeviceDetail.where("created_at >= ?", Date.today).order('created_at desc').paginate(:page => params[:page], :per_page => PER_PAGE)
        end

        def index
          if params[:search]            
            @deviceDetails = DeviceDetail.search(params[:search]).order("created_at desc").paginate(:page => params[:page], :per_page => PER_PAGE)
          else
            #@users = User.all.order('created_at desc').paginate(:page => params[:page], :per_page => PER_PAGE)
            @deviceDetails = DeviceDetail.where("created_at >= ?", Date.today).order('created_at desc').paginate(:page => params[:page], :per_page => PER_PAGE)
          end  
        end

        def show
            @deviceDetail = DeviceDetail.find_by(id:params[:id])
            @qrCodes = RecentlyAdded.where(device_detail_id: @deviceDetail.id).order(id: :desc).paginate(:page => params[:page], :per_page => 10)
            @favourites = Favourite.where(device_detail_id: @deviceDetail.id).order(id: :desc).paginate(:page => params[:page], :per_page => 10)
            @user_id = @deviceDetail.user_detail_id.split(",").last
            @appOpen = AppOpen.where(deviceId: @deviceDetail.deviceId).paginate(:page => params[:page], :per_page => 10)
            if @user_id.present?
                @userDetail = UserDetail.find(@user_id)
                @transactionHistories = @userDetail.transaction_histories.limit(20).order(id: :desc).paginate(:page => params[:page], :per_page => 10)
                @redeems = @userDetail.redeems.limit(20).order(id: :desc).paginate(:page => params[:page], :per_page => 10)
            end
        end
    end
end

app/controllers/admin/login_controller.rb
class Admin::LoginController < ApplicationController
  def new
  end

  def login
    if params[:username] == "admin@gmail.com" && params[:password] == "123"
      session[:admin_authenticated] = true
      redirect_to admin_dashboard_path
    else
      flash.now[:notice] = "Invalid email or password"
      render :new
    end
  end

  def logout
    session[:admin_authenticated] = nil
    redirect_to admin_path, notice: "Logged out successfully!"
  end
end

app/controllers/admin/qr_data_controller.rb
module Admin
    class QrDataController < Admin::AdminController
        before_action :authenticate_user!

        layout "admin"
        def index
            #@qrData = QrDatum.all.order("id DESC").paginate(:page => params[:page], :per_page => 10)
            @qrData = QrDatum.where("created_at >= ?", Date.today).order('created_at desc').paginate(:page => params[:page], :per_page => PER_PAGE)
        end
        def show
            @qrData = QrDatum.find_by(id:params[:id])
        end
    end
end

app/controllers/admin/redeems_controller.rb
module Admin
  class RedeemsController < Admin::AdminController
    before_action :authenticate_user!

    layout "admin"

    def index
      @redeems = Redeem.all.order(id: :desc).paginate(page: params[:page],per_page: PER_PAGE)
    end

    def edit
      @redeem = Redeem.find(params[:id])
    end

    def update
      @redeem = Redeem.find(params[:id])
      if @redeem.update(redeem_params)
        redirect_to admin_user_detail_path(@redeem.user_detail_id)
      else
        render :edit
      end
    end

    private
    def redeem_params
      params.require(:redeem).permit(:status)
    end
  end
end

app/controllers/api/base.rb
module API
  class Base < Grape::API
    mount API::V1::DeviceDetailsApi
    mount API::V1::AppOpenApi
    mount API::V1::HomeApi
    mount API::V1::ScannerDataApi
    mount API::V1::GeneratedQrApi
    mount API::V1::FavouriteApi
    mount API::V1::UserDetails
    mount API::V1::QrDataApi
    mount API::V1::HistoryApi
    mount API::V1::TransactionHistoryApi
    mount API::V1::DefaultUser
    mount API::V1::RewardList
    mount API::V1::RedeemSubmit
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
  end
  
  def invite
  	@referral_code = params['refCode']
  	@playbutton = "market://details?id=com.apps.scanbuddy&referrer=utm_source%3DINVITE%26utm_medium%3D#{@referral_code}%26utm_term%3DINVITE%26utm_content%3DINVITE%26utm_campaign%3DINVITE"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/device_details/index.html.erb
<!-- Page Content -->
<div id="page-wrapper">
  <div class="container-fluid">
    <div class="row">
      <div class="col-lg-12">
        <h2 class="page-header" style="margin: 10px 0 15px !important;">Device Details</h2>
      </div>
      <div class="form-group">
        <%= form_tag('/admin/search-device', :method => "get", id: "search-form") do %>
          <%= text_field_tag :search, params[:search], class: 'form-control', :required => true, placeholder: 'Which Device/Email/refCode you are looking for?' %>
        <% end %>        
      </div>
      <% if @deviceDetails.present? %>
        <table class="table table-responsive table-bordered">
          <thead>
            <tr>
              <th>Id</th>
              <th>Device Name</th>
              <th>Device Id</th>
              <th>Security Token</th>
              <th>Advertising Id</th>
              <th>Action</th>
            </tr>
          </thead>
          <tbody>
            <% @deviceDetails.each do |device| %>
            <tr>
              <td><%= device.id %></td>
              <td><%= device.deviceName %></td>
              <td><%= device.deviceId %></td>
              <td><%= device.security_token %></td>
              <td><%= device.advertisingId %></td>
              <td>
                <%= link_to 'Show', admin_device_detail_path(device) %>
              </td>
            </tr>
            <% end %>
          </tbody>
        </table>
        <%= will_paginate @deviceDetails %>
      <% else %>
        <h1 class="not-found">No Device Found</h1>
      <% end %>
    </div>
    <!-- /.row -->
  </div>
  <!-- /.container-fluid -->
</div>
<!-- /#page-wrapper -->

app/views/admin/device_details/show.html.erb
<!-- Page Content -->
<div id="page-wrapper">
  <div class="container-fluid">
    <div class="row">
      <p id="notice" style="color:orange;"><%= notice %></p>
      <div class="col-lg-12">
        <h2 class="page-header" style="margin: 10px 0 15px !important;">Showing Device Details</h2>
      </div>
      <!-- Device Details Table -->
      <table class="table table-responsive table-bordered">
        <thead>
          <tr>
            <th>Id</th>
            <th>Device Name</th>
            <th>Device Id</th>
            <th>Security Token</th>
            <th>Advertising Id</th>
            <th>Utm Term</th>
            <th>Utm Content</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td><%= @deviceDetail.id %></td>
            <td><%= @deviceDetail.deviceName %></td>
            <td><%= @deviceDetail.deviceId %></td>
            <td><%= @deviceDetail.security_token %></td>
            <td><%= @deviceDetail.advertisingId %></td>
            <td><%= @deviceDetail.utmTerm %></td>
            <td><%= @deviceDetail.utmContent %></td>
          </tr>
        </tbody>
      </table>

      <!-- Additional Device Information Table -->
      <table class="table table-responsive table-bordered">
        <thead>
          <tr>
            <th>Device Type</th>
            <th>Version Name</th>
            <th>Version Code</th>
            <th>Utm Source</th>
            <th>Utm Medium</th>
            <th>Referrer Url</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td><%= @deviceDetail.deviceType %></td>
            <td><%= @deviceDetail.versionName %></td>
            <td><%= @deviceDetail.versionCode %></td>
            <td><%= @deviceDetail.utmSource %></td>
            <td><%= @deviceDetail.utmMedium %></td>
            <td><%= @deviceDetail.referrerUrl %></td>
          </tr>
        </tbody>
      </table>
      
      <!-- User Details Table -->
      <h3>User Details</h3>
            <% if @userDetail.present? %>
              <table class="table table-responsive table-bordered">
                <thead>
                  <tr>
                    <th>Id</th>
                    <th>Social Image</th>
                    <th>Social Id</th>
                    <th>Social Name</th>
                    <th>Social Email</th>
                    <th>Wallet Balance</th>
                    <th>Ref Code</th>
                    <th>Created At</th>
                    <th>Updated At</th>
                  </tr>
                </thead>
                <tbody>
                    <tr>
                      <td><a href="/admin/user_details/<%= @userDetail.id %>"><%= @userDetail.id %></a></td>
                      <td><img style="width:20px;" src="<%=@userDetail.try(:socialImgUrl)%>" onerror="this.onerror=null;this.src='https://cdn.pixabay.com/photo/2014/03/24/17/21/wrong-295503_640.png';" /></td>
                      <td><%= @userDetail.socialId %></td>
                      <td><%= @userDetail.socialName %></td>
                      <td><%= @userDetail.socialEmail %></td>
                      <td><%= @userDetail.wallet_balance %></td>
                      <td><%= @userDetail.refCode %></td>
                      <td><%= @userDetail.created_at.strftime("%d/%m/%y %I:%M %p") %></td>
                      <td><%= @userDetail.updated_at.strftime("%d/%m/%y %I:%M %p") %></td> 
                    </tr>
                </tbody>
              </table>
              <%= will_paginate @qrCodes %>
            <% else %>
              <p>No QR Codes found.</p>
            <% end %>

            <h3>App Opens</h3>
      <% if @appOpen.present? %>
        <table class="table table-responsive table-bordered">
          <thead>
            <tr>
              <th>Id</th>
              <th>Security Token</th>
              <th>Social Name</th>
              <th>Social Email</th>
              <th>Version Name</th>
              <th>Version Code</th>
              <th>Force Update</th>
            </tr>
          </thead>
          <tbody>
            <% @appOpen.each do |app| %>
              <tr>
                <td><%= app.id %></td>
                <td><%= app.securityToken %></td>
                <td><%= app.socialName %></td>
                <td><%= app.socialEmail %></td>
                <td><%= app.versionName %></td>
                <td><%= app.versionCode %></td>
                <td><%= app.forceUpdate %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
        <%= will_paginate @appOpen %>
      <% else %>
        <p>No app open found.</p>
      <% end %>
      


            <h3>User Redeems</h3>
      <% if @redeems.present? %>
        <table class="table table-responsive table-bordered">
          <thead>
            <tr>
              <th>Id</th>
              <th>Mobile Number</th>
              <th>Coins</th>
              <th>Amount</th>
              <th>Pay Type</th>
              <th>Status</th>
              <th>Pay Vendor</th>
              <th>Trans Vendor</th>
              <th>Pay Id</th>
              <th>Action</th>
            </tr>
          </thead>
          <tbody>
            <% @redeems.each do |redeem| %>
              <tr>
                <td><%= redeem.id %></td>
                <td><%= redeem.mobileNumber %></td>
                <td><%= redeem.payCoins %></td>
                <td><%= redeem.payAmount %></td>
                <td><%= redeem.payType %></td>
                <td>
                  <% if redeem.status == "PENDING" %>
                    <p class="text-danger"><%= redeem.status %></p>
                  <% elsif redeem.status == "PROCESSING" %>
                    <p class="text-warning"><%= redeem.status %></p>
                  <% else %>
                    <p class="text-success"><%= redeem.status %></p>
                  <% end %>
                </td>
                <td><%= redeem.payVendor %></td>
                <td><%= redeem.transVendor %></td>
                <td><%= redeem.payId %></td>
                <td ><a href="/admin/redeems/<%= redeem.id %>/edit"><button class="btn btn-primary">Edit</button></a></td>
              </tr>
            <% end %>
          </tbody>
        </table>
        <%= will_paginate @redeems %>
      <% else %>
        <p>No user redeems found.</p>
      <% end %>

       <h3>User Transaction History</h3>
      <% if @transactionHistories.present? %>
        <table class="table table-responsive table-bordered">
          <thead>
            <tr>
              <th>Id</th>
              <th>Title</th>
              <th>Subtitle</th>
              <th>Coins</th>
            </tr>
          </thead>
          <tbody>
            <% @transactionHistories.each do |history| %>
              <tr>
                <td><%= history.id %></td>
                <td><%= history.title %></td>
                <td><%= history.subtitle %></td>
                <td><%= history.coins %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
        <%= will_paginate @transactionHistories %>
      <% else %>
        <p>No user transaction history found.</p>
      <% end %>
      

      <!-- QR Codes Table -->
      <h3>QR Codes</h3>
      <% if @qrCodes.present? %>
        <table class="table table-responsive table-bordered">
          <thead>
            <tr>
              <th>Id</th>
              <th>Title</th>
              <th>Subtitle</th>
              <th>Created At</th>
              <th>Updated At</th>
            </tr>
          </thead>
          <tbody>
            <% @qrCodes.each do |qr| %>
              <tr>
                <td><a href="/admin/recently_addeds/<%= qr.id %>"><%= qr.id %></a></td>
                <td><%= qr.title %></td>
                <td><%= qr.subtitle.truncate(50) %></td>
                <td><%= qr.created_at.strftime("%d/%m/%y %I:%M %p") %></td>
                <td><%= qr.updated_at.strftime("%d/%m/%y %I:%M %p") %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
        <%= will_paginate @qrCodes %>
      <% else %>
        <p>No QR Codes found.</p>
      <% end %>
      
      <!-- Favourites Table -->
      <h3>Favourites</h3>
      <% if @favourites.present? %>
        <table class="table table-responsive table-bordered">
          <thead>
            <tr>
              <th>QR Code Id</th>
              <th>Version Name</th>
              <th>Version Code</th>
              <th>Created At</th>
              <th>Updated At</th>
            </tr>
          </thead>
          <tbody>
            <% @favourites.each do |fav| %>
              <tr>
                <td><%= fav.qr_code_id %></td>
                <td><%= fav.versionName %></td>
                <td><%= fav.versionCode %></td>
                <td><%= fav.created_at.strftime("%d/%m/%y %I:%M %p") %></td>
                <td><%= fav.updated_at.strftime("%d/%m/%y %I:%M %p") %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
        <%= will_paginate @favourites %>
      <% else %>
        <p>No Favourites found.</p>
      <% end %>
    </div>
  </div>
</div>