config/routes.rb
Rails.application.routes.draw do

  root "main#index"
  get "/invite/:refCode" => "main#invite"
  
  get "/admin" => "admin/login#new"
  post "/admin" => "admin/login#login"
  delete "/admin/logout" => "admin/login#logout"
  get "/admin/dashboard" => "admin/dashboard#index"  
  namespace :admin do
      resources :app_banners
      resources :app_opens
      resources :device_details
      resources :favourites
      resources :generated_qrs
      resources :qr_data
      resources :recently_addeds
      resources :redeems
      resources :redeem_histories
      resources :user_details
      get '/search-user' => 'user_details#index'
      get '/search-device' => 'device_details#index'
  end

  mount API::Base => "/"

end

app/models/app_banner.rb
class AppBanner < ApplicationRecord
end

app/models/app_open.rb
class AppOpen < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/device_detail.rb
class DeviceDetail < ApplicationRecord
  has_many :recently_added
  has_many :qr_data
  has_many :generated_qrs
  has_many :favourites
  has_and_belongs_to_many :user_detail

  def self.search(search)
    where("deviceId LIKE ? OR deviceName LIKE ? OR security_token LIKE ? OR advertisingId LIKE ?", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%") 
  end
end

app/models/favourite.rb
class Favourite < ApplicationRecord
  belongs_to :device_detail
end

app/models/generated_qr.rb
class GeneratedQr < ApplicationRecord
  has_one_attached :codeImage
  belongs_to :device_detail
end

app/models/manager.rb
class Manager < ApplicationRecord
  has_secure_password
end

app/models/qr_datum.rb
class QrDatum < ApplicationRecord
  belongs_to :device_detail
end

app/models/recently_added.rb
class RecentlyAdded < ApplicationRecord
  belongs_to :device_detail
end

app/models/redeem.rb
class Redeem < ApplicationRecord
  belongs_to :user_detail
end

app/models/traffic_request.rb
class TrafficRequest < ApplicationRecord
end

app/models/transaction_history.rb
class TransactionHistory < ApplicationRecord
  belongs_to :user_detail
end

app/models/user_detail.rb
class UserDetail < ApplicationRecord
  has_many :transaction_histories
  has_many :redeems
  has_and_belongs_to_many :device_detail

  def self.search(search)
    where("socialEmail LIKE ? OR socialName LIKE ? OR refCode LIKE ? OR advertisingId LIKE ?", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%") 
  end

end

app/controllers/admin/admin_controller.rb
module Admin
  class AdminController < ApplicationController
    PER_PAGE = 25
    
    def authenticate_user!
      redirect_to admin_path unless current_user
    end

    def current_user
      session[:admin_authenticated] == true
    end
  end
end

app/controllers/admin/app_opens_controller.rb
module Admin
    class AppOpensController < Admin::AdminController
        before_action :authenticate_user!
        layout "admin"

        def index
          #@appOpens = AppOpen.all.order("id DESC").paginate(:page => params[:page], :per_page => 10)
          @appOpens = AppOpen.where("created_at >= ?", Date.today).order('created_at desc').paginate(:page => params[:page], :per_page => PER_PAGE)
        end

        def show
          @appOpen = AppOpen.find_by(id: params[:id])
        end
    end
end

app/controllers/admin/login_controller.rb
class Admin::LoginController < ApplicationController
  def new
  end

  def login
    if params[:username] == "admin@gmail.com" && params[:password] == "123"
      session[:admin_authenticated] = true
      redirect_to admin_dashboard_path
    else
      flash.now[:notice] = "Invalid email or password"
      render :new
    end
  end

  def logout
    session[:admin_authenticated] = nil
    redirect_to admin_path, notice: "Logged out successfully!"
  end
end

app/controllers/admin/qr_data_controller.rb
module Admin
    class QrDataController < Admin::AdminController
        before_action :authenticate_user!

        layout "admin"
        def index
            #@qrData = QrDatum.all.order("id DESC").paginate(:page => params[:page], :per_page => 10)
            @qrData = QrDatum.where("created_at >= ?", Date.today).order('created_at desc').paginate(:page => params[:page], :per_page => PER_PAGE)
        end
        def show
            @qrData = QrDatum.find_by(id:params[:id])
        end
    end
end

app/controllers/admin/redeems_controller.rb
module Admin
  class RedeemsController < Admin::AdminController
    before_action :authenticate_user!

    layout "admin"

    def index
      @redeems = Redeem.all.order(id: :desc).paginate(page: params[:page],per_page: PER_PAGE)
    end

    def edit
      @redeem = Redeem.find(params[:id])
    end

    def update
      @redeem = Redeem.find(params[:id])
      if @redeem.update(redeem_params)
        redirect_to admin_user_detail_path(@redeem.user_detail_id)
      else
        render :edit
      end
    end

    private
    def redeem_params
      params.require(:redeem).permit(:status)
    end
  end
end

app/controllers/api/base.rb
module API
  class Base < Grape::API
    mount API::V1::DeviceDetailsApi
    mount API::V1::AppOpenApi
    mount API::V1::HomeApi
    mount API::V1::ScannerDataApi
    mount API::V1::GeneratedQrApi
    mount API::V1::FavouriteApi
    mount API::V1::UserDetails
    mount API::V1::QrDataApi
    mount API::V1::HistoryApi
    mount API::V1::TransactionHistoryApi
    mount API::V1::DefaultUser
    mount API::V1::RewardList
    mount API::V1::RedeemSubmit
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
  end
  
  def invite
  	@referral_code = params['refCode']
  	@playbutton = "market://details?id=com.apps.scanbuddy&referrer=utm_source%3DINVITE%26utm_medium%3D#{@referral_code}%26utm_term%3DINVITE%26utm_content%3DINVITE%26utm_campaign%3DINVITE"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/app_opens/index.html.erb
<div id="page-wrapper">
  <div class="container-fluid">
    <div class="row">
      <div class="col-lg-12">
        <h2 class="page-header" style="margin: 10px 0 15px !important;">App Opens</h2>
      </div>
      <% if @appOpens.present? %>
        <table class="table table-responsive table-bordered">
          <thead>
            <tr>
              <th>Id</th>
              <th>Device Id</th>
              <th>Security Token</th>
              <th>Social Name</th>
              <th>Social Email</th>
              <th>Action</th>
            </tr>
          </thead>
          <tbody>
            <% @appOpens.each do |app| %>
              <tr>
                <td><%= app.id %></td>
                <td><%= app.deviceId %></td>
                <td><%= app.securityToken %></td>
                <td><%= app.socialName %></td>
                <td><%= app.socialEmail %></td>
                <td>
                  <%= link_to 'Show', admin_app_open_path(app) %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
         <%= will_paginate @appOpens %>
      <% else %>
        <h1 class="not-found">No App Opens Found</h1>
      <% end %>
    </div>
    <!-- /.row -->
  </div>
  <!-- /.container-fluid -->
</div>
<!-- /#page-wrapper -->

app/views/admin/app_opens/show.html.erb
<!-- Page Content -->
<div id="page-wrapper">
  <div class="container-fluid">
    <div class="row">
      <p id="notice" style="color:orange;"><%= notice %></p>
      <div class="col-lg-12">
        <h2 class="page-header" style="margin: 10px 0 15px !important;">App Open Details</h2>
      </div>
      
      <!-- App Open Details Table -->
      <% if @appOpen %>
        <table class="table table-responsive table-bordered">
          <thead>
            <tr>
              <th>Id</th>
              <th>Device Id</th>
              <th>Security Token</th>
              <th>Social Name</th>
              <th>Social Email</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td><%= @appOpen.id %></td>
              <td><%= @appOpen.deviceId %></td>
              <td><%= @appOpen.securityToken %></td>
              <td><%= @appOpen.socialName %></td>
              <td><%= @appOpen.socialEmail %></td>
            </tr>
          </tbody>
        </table>

        <!-- Additional App Open Information Table -->
        <table class="table table-responsive table-bordered">
          <thead>
            <tr>
              <th>Version Name</th>
              <th>Version Code</th>
              <th>Social ImgUrl</th>
              <th>App Url</th>
              <th>Force Update</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td><%= @appOpen.versionName %></td>
              <td><%= @appOpen.versionCode %></td>
              <td><a href="<%= @appOpen.socialImgUrl %>"><%= @appOpen.socialImgUrl %></a></td>
              <td><%= @appOpen.app_url %></td>
              <td><%= @appOpen.forceUpdate %></td>
            </tr>
          </tbody>
        </table>
      <% else %>
        <h1 class="not-found">No App Open Found</h1>
      <% end %>
    </div>
  </div>
</div>