config/routes.rb
Rails.application.routes.draw do

  root "main#index"
  get "/invite/:refCode" => "main#invite"
  
  get "/admin" => "admin/login#new"
  post "/admin" => "admin/login#login"
  delete "/admin/logout" => "admin/login#logout"
  get "/admin/dashboard" => "admin/dashboard#index"  
  namespace :admin do
      resources :app_banners
      resources :app_opens
      resources :device_details
      resources :favourites
      resources :generated_qrs
      resources :qr_data
      resources :recently_addeds
      resources :redeems
      resources :redeem_histories
      resources :user_details
      get '/search-user' => 'user_details#index'
      get '/search-device' => 'device_details#index'
  end

  mount API::Base => "/"

end

app/models/app_banner.rb
class AppBanner < ApplicationRecord
end

app/models/app_open.rb
class AppOpen < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/device_detail.rb
class DeviceDetail < ApplicationRecord
  has_many :recently_added
  has_many :qr_data
  has_many :generated_qrs
  has_many :favourites
  has_and_belongs_to_many :user_detail

  def self.search(search)
    where("deviceId LIKE ? OR deviceName LIKE ? OR security_token LIKE ? OR advertisingId LIKE ?", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%") 
  end
end

app/models/favourite.rb
class Favourite < ApplicationRecord
  belongs_to :device_detail
end

app/models/generated_qr.rb
class GeneratedQr < ApplicationRecord
  has_one_attached :codeImage
  belongs_to :device_detail
end

app/models/manager.rb
class Manager < ApplicationRecord
  has_secure_password
end

app/models/qr_datum.rb
class QrDatum < ApplicationRecord
  belongs_to :device_detail
end

app/models/recently_added.rb
class RecentlyAdded < ApplicationRecord
  belongs_to :device_detail
end

app/models/redeem.rb
class Redeem < ApplicationRecord
  belongs_to :user_detail
end

app/models/traffic_request.rb
class TrafficRequest < ApplicationRecord
end

app/models/transaction_history.rb
class TransactionHistory < ApplicationRecord
  belongs_to :user_detail
end

app/models/user_detail.rb
class UserDetail < ApplicationRecord
  has_many :transaction_histories
  has_many :redeems
  has_and_belongs_to_many :device_detail

  def self.search(search)
    where("socialEmail LIKE ? OR socialName LIKE ? OR refCode LIKE ? OR advertisingId LIKE ?", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%") 
  end

end

app/controllers/admin/admin_controller.rb
module Admin
  class AdminController < ApplicationController
    PER_PAGE = 25
    
    def authenticate_user!
      redirect_to admin_path unless current_user
    end

    def current_user
      session[:admin_authenticated] == true
    end
  end
end

app/controllers/admin/app_banners_controller.rb
module Admin
  class AppBannersController < Admin::AdminController
    before_action :authenticate_user!

    layout "admin"

    def index
      @appBanners = AppBanner.all.order("id DESC").paginate(:page => params[:page], :per_page => PER_PAGE)
    end

    def show
      @appBanner = AppBanner.find_by(id: params[:id])
    end

    def new
      @appBanner = AppBanner.new
    end

    def create
      @appBanner = AppBanner.new(app_banner_params)
      if @appBanner.save
        redirect_to admin_app_banner_path(@appBanner)
      else
        render :new
      end
    end

    def edit
      @appBanner = AppBanner.find_by(id: params[:id])
    end

    def update
      @appBanner = AppBanner.find_by(id: params[:id])
      if @appBanner.update(app_banner_params)
        redirect_to admin_app_banner_path(@appBanner)
      else
        render :edit
      end
    end

    def destroy
      @appBanner = AppBanner.find_by(id: params[:id])
      @appBanner.destroy
      redirect_to admin_app_banners_path
    end

    private

    def app_banner_params
      params.require(:app_banner).permit(:imgUrl, :actionUrl, :status)
    end
  end
end

app/controllers/admin/login_controller.rb
class Admin::LoginController < ApplicationController
  def new
  end

  def login
    if params[:username] == "admin@gmail.com" && params[:password] == "123"
      session[:admin_authenticated] = true
      redirect_to admin_dashboard_path
    else
      flash.now[:notice] = "Invalid email or password"
      render :new
    end
  end

  def logout
    session[:admin_authenticated] = nil
    redirect_to admin_path, notice: "Logged out successfully!"
  end
end

app/controllers/admin/qr_data_controller.rb
module Admin
    class QrDataController < Admin::AdminController
        before_action :authenticate_user!

        layout "admin"
        def index
            #@qrData = QrDatum.all.order("id DESC").paginate(:page => params[:page], :per_page => 10)
            @qrData = QrDatum.where("created_at >= ?", Date.today).order('created_at desc').paginate(:page => params[:page], :per_page => PER_PAGE)
        end
        def show
            @qrData = QrDatum.find_by(id:params[:id])
        end
    end
end

app/controllers/admin/redeems_controller.rb
module Admin
  class RedeemsController < Admin::AdminController
    before_action :authenticate_user!

    layout "admin"

    def index
      @redeems = Redeem.all.order(id: :desc).paginate(page: params[:page],per_page: PER_PAGE)
    end

    def edit
      @redeem = Redeem.find(params[:id])
    end

    def update
      @redeem = Redeem.find(params[:id])
      if @redeem.update(redeem_params)
        redirect_to admin_user_detail_path(@redeem.user_detail_id)
      else
        render :edit
      end
    end

    private
    def redeem_params
      params.require(:redeem).permit(:status)
    end
  end
end

app/controllers/api/base.rb
module API
  class Base < Grape::API
    mount API::V1::DeviceDetailsApi
    mount API::V1::AppOpenApi
    mount API::V1::HomeApi
    mount API::V1::ScannerDataApi
    mount API::V1::GeneratedQrApi
    mount API::V1::FavouriteApi
    mount API::V1::UserDetails
    mount API::V1::QrDataApi
    mount API::V1::HistoryApi
    mount API::V1::TransactionHistoryApi
    mount API::V1::DefaultUser
    mount API::V1::RewardList
    mount API::V1::RedeemSubmit
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
  end
  
  def invite
  	@referral_code = params['refCode']
  	@playbutton = "market://details?id=com.apps.scanbuddy&referrer=utm_source%3DINVITE%26utm_medium%3D#{@referral_code}%26utm_term%3DINVITE%26utm_content%3DINVITE%26utm_campaign%3DINVITE"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/app_banners/edit.html.erb
<div id="page-wrapper">
  <h2 class="page-header" style="margin: 10px 0 15px !important;">App Banners</h2>
<div class="container"> 
<%= form_with(model: @appBanner, url: admin_app_banner_path(@appBanner)) do |form| %>
  <% if @appBanner.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@appBanner.errors.count, "error") %> prohibited this app banner from being saved:</h2>
      <ul>
        <% @appBanner.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <!-- /.row -->
    <div class="row">
    <div class="col-lg-10">
      <div class="panel panel-default">
        <div class="panel-heading">
          Basic Form Elements
        </div>
        <div class="panel-body">
          <div class="row">
            <div class="col-lg-6">
              <div class="form-group">
                <label>Image Url</label>
                <%= form.text_field :imgUrl, class: "form-control", placeholder: "Enter image url", required: true %>       
              </div>
              <div class="form-group">
                <label>Action Url</label>
                <%= form.text_field :actionUrl, class: "form-control", placeholder: "Enter action url" %>
              </div>
              <div class="form-group">
                <label>Status</label>
                <%= form.select :status, [['Active', true], ['Inactive', false]], class: 'form-control' %>
              </div>
            </div>

            <!-- /.col-lg-6 (nested) -->
            <div class="col-lg-6">
              <div class="form-group">
                <label>Created At</label>
                <span class="form-control"><%= @appBanner.created_at.strftime("%d/%m/%y %I:%M %p") %></span>
              </div>
              <div class="form-group">
                <label>Updated At</label>
                <span class="form-control"><%= @appBanner.updated_at %></span>
              </div>
              <div class="form-group">
                <%= form.submit "Update", class: "btn btn-primary" %>
                <%= link_to 'Back', admin_app_banners_path, class: "btn btn-default" %>
              </div>
            </div>
            <!-- /.col-lg-6 (nested) -->
          </div>
          <!-- /.row (nested) -->
        </div>
        <!-- /.panel-body -->
      </div>
      <!-- /.panel -->
    </div>
    <!-- /.col-lg-12 -->
  </div>
  <!-- /.row -->
<% end %>
</div>
</div>

app/views/admin/app_banners/index.html.erb
<!-- Page Content -->
<div id="page-wrapper">
  <div class="container-fluid">
    <div class="row">
      <div class="col-lg-12">
        <h2 class="page-header" style="margin: 10px 0 15px !important;">App Banners</h2>
      </div>
      <div class="new" style="margin-bottom: 15px;">
        <%= link_to "New App Banner", new_admin_app_banner_path, class: "btn btn-primary" %>
      </div>
      <% if @appBanners.present? %>
        <table class="table table-responsive table-bordered">
          <thead>
            <tr>
              <th>Id</th>
              <th>Image Url</th>
              <th>Action Url</th>
              <th>Status</th>
              <th>Created At</th>
              <th>Updated At</th>
              <th>Action</th>
            </tr>
          </thead>
          <tbody>
            <% @appBanners.each do |banner| %>
              <tr>
                <td><%= banner.id %></td>
                <td><%= banner.imgUrl[0,60] + "..." %></td>
                <td><%= banner.actionUrl %></td>
                <td>
                  <% if banner.status == false %>
                    <p>❌</p>
                  <% else %>
                    <p>✔️</p>
                  <% end %>
                </td>
                <td><%= banner.created_at.strftime("%d/%m/%y %I:%M %p") %></td>
                <td><%= banner.updated_at.strftime("%d/%m/%y %I:%M %p") %></td>
                <td>
                  <%= link_to 'Show', admin_app_banner_path(banner) %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
         <%= will_paginate @appBanners %>
      <% else %>
        <h1 class="not-found">No App Banners Found</h1>
      <% end %>
    </div>
    <!-- /.row -->
  </div>
  <!-- /.container-fluid -->
</div>
<!-- /#page-wrapper -->

app/views/admin/app_banners/new.html.erb
<div id="page-wrapper">      
<h2 class="page-header" style="margin: 10px 0 15px !important;">App Banners</h2>
<div class="container"> 
<%= form_with(model: @appBanner, url: admin_app_banners_path) do |form| %>
  <% if @appBanner.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@appBanner.errors.count, "error") %> prohibited this app banner from being saved:</h2>
      <ul>
        <% @appBanner.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <!-- /.row -->
    <div class="row">
    <div class="col-lg-10">
      <div class="panel panel-default">
        <div class="panel-heading">
          Basic Form Elements
        </div>
        <div class="panel-body">
          <div class="row">
            <div class="col-lg-6">
              <div class="form-group">
                <label>Image Url</label>
                <%= form.text_field :imgUrl, class: "form-control", placeholder: "Enter image url", required: true %>       
              </div>
              <div class="form-group">
                <label>Action Url</label>
                <%= form.text_field :actionUrl, class: "form-control", placeholder: "Enter action url" %>
              </div>
              <div class="form-group">
                <label>Status</label>
                <%= form.select :status, [['Active', true], ['Inactive', false]], class: 'form-control' %>
              </div>
               <div class="form-group">
                <%= form.submit "Create", class: "btn btn-primary" %>
                <%= link_to 'Back', admin_app_banners_path, class: "btn btn-default" %>
              </div>
            </div>
            
          </div>
          <!-- /.row (nested) -->
        </div>
        <!-- /.panel-body -->
      </div>
      <!-- /.panel -->
    </div>
    <!-- /.col-lg-12 -->
  </div>
  <!-- /.row -->
<% end %>
</div>
</div>

app/views/admin/app_banners/show.html.erb
<!-- Page Content -->
<div id="page-wrapper">
  <div class="container-fluid">
    <div class="row">
      <p id="notice" style="color: orange;"><%= notice %></p>
      <div class="col-lg-12">
        <h2 class="page-header" style="margin: 10px 0 15px !important;">Showing App Banner</h2>
      </div>
      
      <!-- App Banner Details Table -->
      <table class="table table-responsive table-bordered">
        <thead>
          <tr>
            <th>Id</th>
            <th>Image Url</th>
            <th>Action Url</th>
            <th>Status</th>
            <th>Created At</th>
            <th>Updated At</th>
            <th>Action</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td><%= @appBanner.id %></td>
            <td><a href="<%= @appBanner.imgUrl %>"><%= @appBanner.imgUrl %></a></td>
            <td><%= @appBanner.actionUrl %></td>
            <td>
              <% if @appBanner.status == false %>
                ❌
              <% else %>
                ✔️
              <% end %>
            </td>
            <td><%= @appBanner.created_at.strftime("%d/%m/%y %I:%M %p") %></td>
            <td><%= @appBanner.updated_at.strftime("%d/%m/%y %I:%M %p") %></td>
            <td class="app-banner-action" style="display: flex;gap:5px;">
              <%= link_to 'Edit', edit_admin_app_banner_path(@appBanner), class: "btn btn-primary" %>
              <%= button_to 'Delete', admin_app_banner_path(@appBanner), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>